### ISSUE TITLE
List of projects that use MacDriver

### ISSUE THREAD

**Issue by programmingkidx** [progrium/macdriver#138]
We need a page that lists all know projects that use MacDriver. This will help convince people MacDriver is ready for production work.

**Comment by cweagans** [comment]
https://deps.dev/go/github.com%2Fprogrium%2Fmacdriver/v0.4.0/dependents perhaps?

**Comment by programmingkidx** [comment]
@cweagans Thank you for this.

**Comment by progrium** [comment]
It's pre-1.0 for a reason. I think after 0.5 we'll be pretty close to a 1.0 RC. I have not found or heard of any major projects using MacDriver, and I agree we should share a list if they do exist. But it might still be too early. I will solicit for projects using it after the 0.5 release and the name change because at least at that point there will be a release that *I* would consider building on if this weren't my project.
