### ISSUE TITLE
Feature request: Make NSControl's SetAction() accept Go functions

### ISSUE THREAD

**Issue by programmingkidx** [progrium/macdriver#161]
NSControl's SetAction: method expects a selector in order to set a control's action method. Since this is Go I request that SetAction be changed to be able to accept a Go function directly. What I am hoping for is to be able to connect a Go function to a control's action property without having to use any Objective-C construct. I really think this would make using the Appkit easier and more Go-like.

**Comment by progrium** [comment]
I agree that would be nice. However, there are over 6000 classes and protocols in Apple's frameworks and there are many different ways they express inversion of control, whether through object selectors, delegates, subclassing, or already just callbacks. Since we're leaning into code generation, any proposal like this should be considered systemically and not just for a single API. Any proposal like this should also allow you to still use the documented mechanism (what if you *do* have an object and not a callback).

While direct translations of equivalent types for convenience is something I'm hesitant about, I'm basically not interested in *changing* the structure and semantics of the APIs for convenience. I would recommend developing your own convenience abstraction for now and if it ends up being useful across lots of instances of this kind of API, we could include it in a helper package.

**Comment by programmingkidx** [comment]
I like the idea of keeping the MacDriver API consistent with the standard. But we don't have to eliminate the standard behavior for NSControl's SetAction() method to be able to use Go functions. We can have both! Using Go's generics feature we can use both a selector and a Go function in the same method. People who want to use a selector in SetAction() can still go through the work of trying to figure out how to do so, and people who just want to connect a Go function to a button and move on could do so also.

**Comment by progrium** [comment]
I'm not sure generics work the way you think for methods, it's a little different than other languages. But I do encourage you to explore abstractions that work for this and other cases that don't depend on changing the bindings API as a way to research and experiment towards a real proposal.

**Comment by programmingkidx** [comment]
It does sound like you would like to keep NSControl's SetAction() as it is. Would you be open to adding a method to NSControl called SetFunction() that would accept a Go function as an argument? This method would be like SetAction() but more go-friendly and easier to use.

**Comment by progrium** [comment]
Not at this time.
