### ISSUE TITLE
integrate objc `release` with Go garbage collector

### ISSUE THREAD

**Issue by progrium** [progrium/macdriver#49]
as [mentioned](https://github.com/progrium/macdriver/issues/12#issuecomment-774351375) in #12, not using a pointer for [`type object`](https://github.com/progrium/macdriver/blob/main/objc/object.go#L80) means its passed as a value. i believe the suggestion was to use it as a pointer type so we could use SetFinalizer effectively. however, this brings up some questions.

since `sendMsg` [creates (maybe all) object values](https://github.com/progrium/macdriver/blob/main/objc/msg_amd64.go#L230), would we want to track those pointer values so there is only one object in go holding reference to an objc pointer?

would this negate the need for using autoreleasepool at all?

**Comment by mgood** [comment]
IIUC I do think we'll want to structure it so that there's only one Go value holding each objc reference. Though if multiple objc calls return references to the same object, each reference would be unique. So as each Go reference is GC-ed, it will `release` the objc, decrementing its reference count, and eventually freeing the object.

However, it doesn't sound like this removes the need for an autoreleasepool. Releasing the Go references would handle objects that are passed back to Go as a return value. However, an objc call may allocate additional objects that are added to the pool, but not directly referenced by the return value. So, calling `release` on the return value would not also release those values.

I'll follow up on #12 with some additional thoughts.

**Comment by mgood** [comment]
Hmm, so I think there's an issue here with how the package currently handles some primitive values. E.g. calls to `Send()` that return raw numeric values still wrap it in an `Object`, where the caller is expected to use `.Int()` to convert it. But for these, the wrapping `Object` instance doesn't know that the `ptr` value is really just a number and not a pointer. So calling `Release()` in the finalizer would crash.

So, it seems like this is first going to require some changes to how it wraps return values to distinguish which are wrapping pointers vs raw values.

**Comment by progrium** [comment]
Yea, there is some simplicity to just assuming objects, esp since most of the APIs are just returning objects. In a way, letting the caller decide to Release gets around this as well. I'm ok with the idea of saying all return values, whether values or objects, will be objects, but once it starts impacting any magic we do with releasing it makes things more complicated. 

Also keep in mind we will have access to schema information for APIs, so when we create wrappers in Go we can decide based on the return value type to do one thing or another.

**Comment by progrium** [comment]
We could say that Go GC integration via finalizer is only done with wrapped/generated code and do it there and not at the `objc` package level.

**Comment by mgood** [comment]
> We could say that Go GC integration via finalizer is only done with wrapped/generated code and do it there and not at the `objc` package level.

Yeah, that could be interesting, and also led me to thinking about a simpler way to just wrap the `Object` interface to add the GC functionality in #51.
We can leave the `objc` package a little lower-level and move the automated memory management into the wrapper layer with some of the helpers.

**Comment by progrium** [comment]
Going to close this for now since it should all be covered now:
https://github.com/progrium/macdriver/blob/main/docs/memorymanagement.md

But we can open a new issue for anything else from here.
